sudo: required

language: python

python:
  - "3.6"

services:
  - docker

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    # Variables found by default in Docker Hub builder
    - DOCKER_REPO=trustcode/doodba-trustcode
  matrix:
    - DOCKER_TAG=11.0

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confnew install docker-ce
  - pip install -r requirements.txt

install:
  - chown -R $USER:$USER .
  - chmod -R +r .
  - ./hooks/build
